### ISSUE TITLE
app router currently doesn't support grafana url namespace

### ISSUE THREAD

**Issue by hatmatter** [socrata-platform/grafana-docker#4]
The app router automatically routes urls that begin with /api/ to the core service. This conflicts with grafana's url scheme and thus requests cannot be sent to grafana's api via the app router while this rule is in place. My currently planned workaround is to not run grafana in mesos.

**Comment by znep** [comment]
Can we work around that by just moving the `app.marathon` host ACLs section earlier in the config in `socrata-consul-template`?  Seems reasonable that a host header should override any path.

Really it doesn't seem like the actual marathon-app-router should have the core specific rules at all though, they should be reserved for the frontend lbs.

```
<% @config['backends'].reject { |be| be.start_with? 'chef_' || be == 'balboa-http-2012' }.each do |backend_name| -%>
  acl <%= backend_name %>_acl hdr_sub(Host) <%= backend_name %>.app.<%= node.chef_environment %>.socrata.net
  acl <%= backend_name %>_dep_acl hdr_sub(Host) <%= backend_name %>.app.marathon.<%= node.chef_environment %>.socrata.net
  <% end %>
```

**Comment by znep** [comment]
Can we work around that by just moving the `app.marathon` host ACLs section earlier in the config in `socrata-consul-template`?  Seems reasonable that a host header should override any path.

Really it doesn't seem like the actual marathon-app-router should have the core specific rules at all though, they should be reserved for the frontend lbs.

**Comment by nmeyerhans** [comment]
As a short-term workaround, why not just bypass the app router and hit the
.consul name? e.g. grafana.aws-us-west-2-staging.socrata.consul

You'll need to explicitly hit whatever port the service listens on.
